In [2]:
!pip3 install neattext
import pandas as pd
import neattext.functions as nfx
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity,linear_kernel

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: neattext in /usr/local/lib/python3.8/dist-packages (0.1.3)

In [3]:
!mkdir ~/.kaggle
!touch ~/.kaggle/kaggle.json

api_token = api_token = {"username":"<username>","key":"<key>"}

import json

with open('/root/.kaggle/kaggle.json', 'w') as file:
    json.dump(api_token, file)

!chmod 600 ~/.kaggle/kaggle.json

In [4]:
! kaggle datasets download -d die9origephit/amazon-data-science-books
! unzip amazon-data-science-books.zip

Downloading amazon-data-science-books.zip to /content
100% 107k/107k [00:00<00:00, 522kB/s]
100% 107k/107k [00:00<00:00, 521kB/s]
Archive:  amazon-data-science-books.zip
  inflating: final_book_dataset_kaggle2.csv

In [16]:
df = pd.read_csv('/content/final_book_dataset_kaggle2.csv')
df.head()

,title,author,price,price (including used books),pages,avg_reviews,n_reviews,star5,star4,star3,star2,star1,dimensions,weight,language,publisher,ISBN_13,link,complete_link
0,Data Analysis Using R (Low Priced Edition): A ...,[ Dr Dhaval Maheta],6.75,6.75,500,4.4,23,55%,39%,6%,NaN,NaN,8.5 x 1.01 x 11 inches,2.53 pounds,English,"Notion Press Media Pvt Ltd (November 22, 2021)",978-1685549596,/Data-Analysis-Using-Low-Priced/dp/1685549594/...,https://www.amazon.com/Data-Analysis-Using-Low...
1,Head First Data Analysis: A learner's guide to...,NaN,33.72,21.49 - 33.72,484,4.3,124,61%,20%,9%,4%,6%,8 x 0.98 x 9.25 inches,1.96 pounds,English,"O'Reilly Media; 1st edition (August 18, 2009)",978-0596153939,/Head-First-Data-Analysis-statistics/dp/059615...,https://www.amazon.com/Head-First-Data-Analysi...
2,Guerrilla Data Analysis Using Microsoft Excel:...,"[ Oz du Soleil, and , Bill Jelen]",32.07,32.07,274,4.7,10,87%,13%,NaN,NaN,NaN,8.25 x 0.6 x 10.75 inches,1.4 pounds,English,"Holy Macro! Books; Third edition (August 1, 2022)",978-1615470747,/Guerrilla-Analysis-Using-Microsoft-Excel/dp/1...,https://www.amazon.com/Guerrilla-Analysis-Usin...
3,Python for Data Analysis: Data Wrangling with ...,[ William McKinney],53.99,53.99,547,4.6,"1,686",75%,16%,5%,2%,2%,7 x 1.11 x 9.19 inches,1.47 pounds,English,"O'Reilly Media; 2nd edition (November 14, 2017)",978-1491957660,/Python-Data-Analysis-Wrangling-IPython/dp/149...,https://www.amazon.com/Python-Data-Analysis-Wr...
4,Excel Data Analysis For Dummies (For Dummies (...,[ Paul McFedries],24.49,24.49,368,3.9,12,52%,17%,10%,10%,10%,7.38 x 0.83 x 9.25 inches,1.3 pounds,English,"For Dummies; 5th edition (February 3, 2022)",978-1119844426,/Excel-Data-Analysis-Dummies-Computer/dp/11198...,https://www.amazon.com/Excel-Data-Analysis-Dum...

In [17]:
 df['title'].iloc[1:5]

1    Head First Data Analysis: A learner's guide to...
2    Guerrilla Data Analysis Using Microsoft Excel:...
3    Python for Data Analysis: Data Wrangling with ...
4    Excel Data Analysis For Dummies (For Dummies (...
Name: title, dtype: object

**Remove Stopwords**


**Remove special characters**

In [18]:
df = df.drop_duplicates(subset=['title'])

df['clean_title'] = df['title'].astype(str)

df['clean_title'] = df['clean_title'].apply(nfx.remove_stopwords)

df['clean_title'] = df['clean_title'].apply(nfx.remove_special_characters)

df['clean_title'].iloc[1:5]

1    Head Data Analysis learners guide big numbers ...
2    Guerrilla Data Analysis Microsoft Excel Overco...
3    Python Data Analysis Data Wrangling Pandas Num...
4    Excel Data Analysis Dummies For Dummies Comput...
Name: clean_title, dtype: object

In [19]:
countvect = CountVectorizer()

cv_mat = countvect.fit_transform(df['clean_title'])

cv_mat

<830x1745 sparse matrix of type '<class 'numpy.int64'>'
	with 6787 stored elements in Compressed Sparse Row format>

In [20]:
df_cv_words = pd.DataFrame(cv_mat.todense(),columns=countvect.get_feature_names())

df_cv_words

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,01,10,100,101,1020gal3040gal,11,1181x2519,12,128,13,...,xai,xgboost,you,young,your,youre,zed,zero,zipline,zoo
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
826,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
827,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
828,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
829,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [21]:
cosine_sim_mat = cosine_similarity(cv_mat)

In [41]:
from pathlib import Path

class RecommendBooks:
  def __init__(self):
    #create a dataframe 
    dirname = Path.cwd().as_posix()
    df = pd.read_csv(dirname+'/final_book_dataset_kaggle2.csv')

    #drop duplicates from the course_title column
    df = df.drop_duplicates(subset=['title'])
    # clean_title column to string from course_title
    df['clean_title'] = df['title'].astype(str)
    # clean_title remove stopwords
    df['clean_title'] = df['clean_title'].apply(nfx.remove_stopwords)
    # clean_title remove special characters
    df['clean_title'] = df['clean_title'].apply(nfx.remove_special_characters)

    # create CountVectorizer
    countvect = CountVectorizer()
    cv_mat = countvect.fit_transform(df['clean_title'])

    # create CV words
    df_cv_words = pd.DataFrame(cv_mat.todense(),columns=countvect.get_feature_names())
    self.df = df
    self.cosine_sim_mat = cosine_similarity(cv_mat)
    print("Data loaded Successfully")

  def autocomplete(self,query):
    result = self.df.loc[self.df['clean_title'].str.contains(query, case=False)]
    data = []
    index = 0
    for obj in result["title"][0:5]:
      data.append({
          "key":index,
          "value":obj
      })
      index = index + 1
    return data
  
  def recommend_books(self,title,numrec = 10):
    course_index = pd.Series( self.df.index, index=self.df['title']).drop_duplicates()
    if title in course_index:
      index = course_index[title]
      scores = list(enumerate(self.cosine_sim_mat [index]))
      sorted_scores = sorted(scores, key=lambda x: x[1], reverse=True)
      selected_course_index = [i[0] for i in sorted_scores[1:]]
      selected_course_score = [i[1] for i in sorted_scores[1:]]
      rec_df = self.df.iloc[selected_course_index]
      rec_df['Similarity_Score'] = selected_course_score
      final_recommended_courses = rec_df[['title', 'Similarity_Score', 'link']]
      result = final_recommended_courses.head(numrec)
      return result
      #parsed = json.loads(result)
      #return {"error":None,"data":parsed}
    else:
      return {"error": "course with title name "+title+" not found"}

In [43]:
recommend = RecommendBooks()
recommend.autocomplete("python")

Data loaded Successfully

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

[{'key': 0,
  'value': 'Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython'},
 {'key': 1,
  'value': "Python for Beginners: 2 Books in 1: The Perfect Beginner's Guide to Learning How to Program with Python with a Crash Course + Workbook"},
 {'key': 2, 'value': 'Monty Python And The Holy Grail'},
 {'key': 3, 'value': 'Python in easy steps'},
 {'key': 4,
  'value': 'Python para Principiantes: 2 Libros en 1: Programación de Python para principiantes + Libro de trabajo de Python (Spanish Edition)'}]

In [47]:
recommend.recommend_books("Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython")

<ipython-input-41-0effb8c1ca4b>:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rec_df['Similarity_Score'] = selected_course_score

,title,Similarity_Score,link
366,Python for Data Analysis: Data Wrangling with ...,0.900000,/Python-Data-Analysis-Wrangling-Jupyter/dp/109...
305,Hands-On Data Analysis with Pandas: A Python d...,0.725319,/Hands-Data-Analysis-Pandas-visualization/dp/1...
58,Hands-On Data Analysis with Pandas: Efficientl...,0.711512,/Hands-Data-Analysis-Pandas-visualization-eboo...
209,Pandas for Everyone: Python Data Analysis (Add...,0.667424,/Pandas-Everyone-Analysis-Addison-Wesley-Analy...
199,"Python Data Analysis: Perform data collection,...",0.659380,/gp/slredirect/picassoRedirect.html/ref=pa_sp_...
192,Python NumPy for Beginners: NumPy Specializati...,0.657376,/Python-NumPy-Beginners-Specialization-Analysi...
312,PYTHON FOR DATA ANALYSIS: Master the Basics of...,0.645497,/PYTHON-DATA-ANALYSIS-Step-Step-ebook/dp/B07P6...
253,Data Analysis from Scratch Python: 2 Books in ...,0.641427,/Data-Analysis-Scratch-Python-Finance-ebook/dp...
86,Data for All,0.632456,/Data-All-John-K-Thompson/dp/1633438775/ref=sr...
335,Data Analysis with Python and PySpark,0.632456,/Analysis-Python-PySpark-Jonathan-Rioux/dp/161...